// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>PlexWebProtocol</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace PlexMediaCenter.Plex.Data.Types {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class user {
        
        private string usernameField;
        
        private string emailField;
        
        private string authenticationtokenField;
        
        private string joinedatField;
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("authentication-token", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authenticationtoken {
            get {
                return this.authenticationtokenField;
            }
            set {
                this.authenticationtokenField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("joined-at", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string joinedat {
            get {
                return this.joinedatField;
            }
            set {
                this.joinedatField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Genre {
        
        private string tagField;
        
        private string idField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Media {
        
        private List<MediaPart> partField;
        
        private string idField;
        
        private string durationField;
        
        private string bitrateField;
        
        private string aspectRatioField;
        
        private string audioChannelsField;
        
        private string audioCodecField;
        
        private string videoCodecField;
        
        private string videoResolutionField;
        
        private string containerField;
        
        private string videoFrameRateField;
        
        public Media() {
            this.partField = new List<MediaPart>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Part", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public List<MediaPart> Part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bitrate {
            get {
                return this.bitrateField;
            }
            set {
                this.bitrateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string aspectRatio {
            get {
                return this.aspectRatioField;
            }
            set {
                this.aspectRatioField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string audioChannels {
            get {
                return this.audioChannelsField;
            }
            set {
                this.audioChannelsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string audioCodec {
            get {
                return this.audioCodecField;
            }
            set {
                this.audioCodecField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string videoCodec {
            get {
                return this.videoCodecField;
            }
            set {
                this.videoCodecField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string videoResolution {
            get {
                return this.videoResolutionField;
            }
            set {
                this.videoResolutionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string videoFrameRate {
            get {
                return this.videoFrameRateField;
            }
            set {
                this.videoFrameRateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaPart {
        
        private List<MediaPartStream> streamField;
        
        private string idField;
        
        private string keyField;
        
        private string durationField;
        
        private string fileField;
        
        private string sizeField;
        
        public MediaPart() {
            this.streamField = new List<MediaPartStream>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Stream", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public List<MediaPartStream> Stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaPartStream {
        
        private string idField;
        
        private string streamTypeField;
        
        private string codecField;
        
        private string indexField;
        
        private string selectedField;
        
        private string keyField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string streamType {
            get {
                return this.streamTypeField;
            }
            set {
                this.streamTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codec {
            get {
                return this.codecField;
            }
            set {
                this.codecField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MediaContainer {
        
        private List<MediaContainerServer> serverField;
        
        private List<MediaContainerDirectory> directoryField;
        
        private List<MediaContainerVideo> videoField;
        
        private List<MediaContainerPhoto> photoField;
        
        private List<MediaContainerTrack> trackField;
        
        private string sizeField;
        
        private string grandparentTitleField;
        
        private string mediaTagPrefixField;
        
        private string mediaTagVersionField;
        
        private string nocacheField;
        
        private string bannerField;
        
        private string parentIndexField;
        
        private string parentTitleField;
        
        private string parentYearField;
        
        private string thumbField;
        
        private string viewGroupField;
        
        private string viewModeField;
        
        private string keyField;
        
        private string artField;
        
        private string title1Field;
        
        private string title2Field;
        
        private string identifierField;
        
        private string friendlyNameField;
        
        private string machineIdentifierField;
        
        private string transcoderActiveVideoSessionsField;
        
        private string transcoderVideoBitratesField;
        
        private string transcoderVideoQualitiesField;
        
        private string transcoderVideoResolutionsField;
        
        private string versionField;
        
        public MediaContainer() {
            this.trackField = new List<MediaContainerTrack>();
            this.photoField = new List<MediaContainerPhoto>();
            this.videoField = new List<MediaContainerVideo>();
            this.directoryField = new List<MediaContainerDirectory>();
            this.serverField = new List<MediaContainerServer>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Server", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public List<MediaContainerServer> Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Directory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public List<MediaContainerDirectory> Directory {
            get {
                return this.directoryField;
            }
            set {
                this.directoryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Video", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public List<MediaContainerVideo> Video {
            get {
                return this.videoField;
            }
            set {
                this.videoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Photo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public List<MediaContainerPhoto> Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Track", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public List<MediaContainerTrack> Track {
            get {
                return this.trackField;
            }
            set {
                this.trackField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grandparentTitle {
            get {
                return this.grandparentTitleField;
            }
            set {
                this.grandparentTitleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mediaTagPrefix {
            get {
                return this.mediaTagPrefixField;
            }
            set {
                this.mediaTagPrefixField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mediaTagVersion {
            get {
                return this.mediaTagVersionField;
            }
            set {
                this.mediaTagVersionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nocache {
            get {
                return this.nocacheField;
            }
            set {
                this.nocacheField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string banner {
            get {
                return this.bannerField;
            }
            set {
                this.bannerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentIndex {
            get {
                return this.parentIndexField;
            }
            set {
                this.parentIndexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentTitle {
            get {
                return this.parentTitleField;
            }
            set {
                this.parentTitleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentYear {
            get {
                return this.parentYearField;
            }
            set {
                this.parentYearField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewGroup {
            get {
                return this.viewGroupField;
            }
            set {
                this.viewGroupField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewMode {
            get {
                return this.viewModeField;
            }
            set {
                this.viewModeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title1 {
            get {
                return this.title1Field;
            }
            set {
                this.title1Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title2 {
            get {
                return this.title2Field;
            }
            set {
                this.title2Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string friendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string machineIdentifier {
            get {
                return this.machineIdentifierField;
            }
            set {
                this.machineIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transcoderActiveVideoSessions {
            get {
                return this.transcoderActiveVideoSessionsField;
            }
            set {
                this.transcoderActiveVideoSessionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transcoderVideoBitrates {
            get {
                return this.transcoderVideoBitratesField;
            }
            set {
                this.transcoderVideoBitratesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transcoderVideoQualities {
            get {
                return this.transcoderVideoQualitiesField;
            }
            set {
                this.transcoderVideoQualitiesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transcoderVideoResolutions {
            get {
                return this.transcoderVideoResolutionsField;
            }
            set {
                this.transcoderVideoResolutionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        [XmlIgnore]
        public Uri UriSource { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerServer {
        
        private string nameField;
        
        private string addressField;
        
        private string portField;
        
        private string hostField;
        
        private string machineIdentifierField;
        
        private string createdAtField;
        
        private string updatedAtField;
        
        private string ownedField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string machineIdentifier {
            get {
                return this.machineIdentifierField;
            }
            set {
                this.machineIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string createdAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owned {
            get {
                return this.ownedField;
            }
            set {
                this.ownedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerDirectory {
        
        private List<MediaContainerDirectoryLocation> locationField;
        
        private List<Genre> genreField;
        
        private string ratingKeyField;
        
        private string keyField;
        
        private string studioField;
        
        private string typeField;
        
        private string titleField;
        
        private string contentRatingField;
        
        private string summaryField;
        
        private string indexField;
        
        private string ratingField;
        
        private string yearField;
        
        private string thumbField;
        
        private string artField;
        
        private string bannerField;
        
        private string durationField;
        
        private string originallyAvailableAtField;
        
        private string leafCountField;
        
        private string viewedLeafCountField;
        
        private string updatedAtField;
        
        private string promptField;
        
        private string searchField;
        
        private string refreshingField;
        
        private string agentField;
        
        private string scannerField;
        
        private string languageField;
        
        private string parentTitleField;
        
        public MediaContainerDirectory() {
            this.genreField = new List<Genre>();
            this.locationField = new List<MediaContainerDirectoryLocation>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public List<MediaContainerDirectoryLocation> Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Genre", Order=1)]
        public List<Genre> Genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ratingKey {
            get {
                return this.ratingKeyField;
            }
            set {
                this.ratingKeyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string studio {
            get {
                return this.studioField;
            }
            set {
                this.studioField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentRating {
            get {
                return this.contentRatingField;
            }
            set {
                this.contentRatingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string banner {
            get {
                return this.bannerField;
            }
            set {
                this.bannerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string originallyAvailableAt {
            get {
                return this.originallyAvailableAtField;
            }
            set {
                this.originallyAvailableAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string leafCount {
            get {
                return this.leafCountField;
            }
            set {
                this.leafCountField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewedLeafCount {
            get {
                return this.viewedLeafCountField;
            }
            set {
                this.viewedLeafCountField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prompt {
            get {
                return this.promptField;
            }
            set {
                this.promptField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string search {
            get {
                return this.searchField;
            }
            set {
                this.searchField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refreshing {
            get {
                return this.refreshingField;
            }
            set {
                this.refreshingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scanner {
            get {
                return this.scannerField;
            }
            set {
                this.scannerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentTitle {
            get {
                return this.parentTitleField;
            }
            set {
                this.parentTitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerDirectoryLocation {
        
        private string pathField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerVideo {
        
        private List<Media> mediaField;
        
        private List<Genre> genreField;
        
        private List<MediaContainerVideoDirector> directorField;
        
        private List<MediaContainerVideoField> fieldField;
        
        private string ratingKeyField;
        
        private string keyField;
        
        private string guidField;
        
        private string studioField;
        
        private string typeField;
        
        private string titleField;
        
        private string contentRatingField;
        
        private string summaryField;
        
        private string ratingField;
        
        private string yearField;
        
        private string taglineField;
        
        private string thumbField;
        
        private string artField;
        
        private string durationField;
        
        private string originallyAvailableAtField;
        
        private string addedAtField;
        
        private string updatedAtField;
        
        private string grandparentKeyField;
        
        private string grandparentTitleField;
        
        private string indexField;
        
        private string parentIndexField;
        
        private string viewOffsetField;
        
        private string viewCountField;
        
        public MediaContainerVideo() {
            this.fieldField = new List<MediaContainerVideoField>();
            this.directorField = new List<MediaContainerVideoDirector>();
            this.genreField = new List<Genre>();
            this.mediaField = new List<Media>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Media", Order=0)]
        public List<Media> Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Genre", Order=1)]
        public List<Genre> Genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Director", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public List<MediaContainerVideoDirector> Director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public List<MediaContainerVideoField> Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ratingKey {
            get {
                return this.ratingKeyField;
            }
            set {
                this.ratingKeyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string studio {
            get {
                return this.studioField;
            }
            set {
                this.studioField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentRating {
            get {
                return this.contentRatingField;
            }
            set {
                this.contentRatingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tagline {
            get {
                return this.taglineField;
            }
            set {
                this.taglineField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string originallyAvailableAt {
            get {
                return this.originallyAvailableAtField;
            }
            set {
                this.originallyAvailableAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string addedAt {
            get {
                return this.addedAtField;
            }
            set {
                this.addedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grandparentKey {
            get {
                return this.grandparentKeyField;
            }
            set {
                this.grandparentKeyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grandparentTitle {
            get {
                return this.grandparentTitleField;
            }
            set {
                this.grandparentTitleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentIndex {
            get {
                return this.parentIndexField;
            }
            set {
                this.parentIndexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewOffset {
            get {
                return this.viewOffsetField;
            }
            set {
                this.viewOffsetField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viewCount {
            get {
                return this.viewCountField;
            }
            set {
                this.viewCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerVideoDirector {
        
        private string idField;
        
        private string tagField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerVideoField {
        
        private string nameField;
        
        private string lockedField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerPhoto {
        
        private List<Media> mediaField;
        
        private List<MediaContainerPhotoField> fieldField;
        
        private string ratingKeyField;
        
        private string keyField;
        
        private string typeField;
        
        private string titleField;
        
        private string contentRatingField;
        
        private string summaryField;
        
        private string ratingField;
        
        private string yearField;
        
        private string thumbField;
        
        private string artField;
        
        private string originallyAvailableAtField;
        
        private string addedAtField;
        
        private string updatedAtField;
        
        private string grandparentKeyField;
        
        private string grandparentTitleField;
        
        private string indexField;
        
        private string parentIndexField;
        
        public MediaContainerPhoto() {
            this.fieldField = new List<MediaContainerPhotoField>();
            this.mediaField = new List<Media>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Media", Order=0)]
        public List<Media> Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public List<MediaContainerPhotoField> Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ratingKey {
            get {
                return this.ratingKeyField;
            }
            set {
                this.ratingKeyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentRating {
            get {
                return this.contentRatingField;
            }
            set {
                this.contentRatingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string originallyAvailableAt {
            get {
                return this.originallyAvailableAtField;
            }
            set {
                this.originallyAvailableAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string addedAt {
            get {
                return this.addedAtField;
            }
            set {
                this.addedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grandparentKey {
            get {
                return this.grandparentKeyField;
            }
            set {
                this.grandparentKeyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grandparentTitle {
            get {
                return this.grandparentTitleField;
            }
            set {
                this.grandparentTitleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentIndex {
            get {
                return this.parentIndexField;
            }
            set {
                this.parentIndexField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerPhotoField {
        
        private string nameField;
        
        private string lockedField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerTrack {
        
        private List<Media> mediaField;
        
        private List<MediaContainerTrackField> fieldField;
        
        private string ratingKeyField;
        
        private string keyField;
        
        private string typeField;
        
        private string titleField;
        
        private string summaryField;
        
        private string indexField;
        
        private string durationField;
        
        private string updatedAtField;
        
        private string guidField;
        
        private string addedAtField;
        
        public MediaContainerTrack() {
            this.fieldField = new List<MediaContainerTrackField>();
            this.mediaField = new List<Media>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Media", Order=0)]
        public List<Media> Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public List<MediaContainerTrackField> Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ratingKey {
            get {
                return this.ratingKeyField;
            }
            set {
                this.ratingKeyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string addedAt {
            get {
                return this.addedAtField;
            }
            set {
                this.addedAtField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaContainerTrackField {
        
        private string nameField;
        
        private string lockedField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
    }
}
